### ISSUE TITLE
Add Twitter and OpenGraph meta tags to head

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#134]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

This might be good for the site SEO.

Add Twitter and OpenGraph meta tags into the head.

### Expected Behavior

Good or best SEO.

This is a common thing in WordPress sites. 

For anyone wondering, there is a freecodecamp lesson on doing this.

### Steps to Reproduce

Try it.

**Comment by Aman0307** [comment]
@gbowne1  I would like to contribute to this issue.

**Comment by gbowne1** [comment]
Ok @Aman0307.  Thanks.

I have assigned you.

**Comment by Aman0307** [comment]
@gbowne1 I have created a pull request. Please do the needful.

**Comment by gbowne1** [comment]
Thanks for the PR.  I have merged.  It will need some fine tuning but the context is there to do so.
